.vim

diff --git a/dotfiles/zsh/func b/dotfiles/zsh/func
--- a/dotfiles/zsh/func
+++ b/dotfiles/zsh/func
@@ -2,9 +2,21 @@
 
 # Easy watching Tv Series
 tv() {
-    vlc "$1" 2>/dev/null 1>&2 &
+    if [ -f "$1" ]; then
+        vlc "$1" 2>/dev/null 1>&2 &
+    else
+        echo "$1 not found"
+    fi
 }
 
+# Listening music
+ctv() {
+    if [ -f "$1" ]; then
+        cvlc "$1" 2>/dev/null 1>&2 &
+    else
+        echo "$1 not found"
+    fi
+}
 # For project Euler
 euler() {
 	gcc -std=c99 -g "$1.c" -lm -o "$1" && ./$1
